### ISSUE TITLE
テスト時に生成された画像が残ってしまう問題

### ISSUE THREAD

**Issue by harune-pg** [cat-katsushika/project7#15]
開発環境でテスト実行後に、テスト中に作成された画像がmediaフォルダに残ってしまう。
テスト以外の通常時に作成された画像と同じ場所に保存されるので、修正したい。

**Comment by pg-endokenta** [comment]
tearDownでテスト毎に削除するのが良さそう

**Comment by harune-pg** [comment]
画像をバックエンドで持たなくなったので、このissueは閉じます

**Comment by harune-pg** [comment]
閉じ方間違えた
